### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by TakenakaEri** [TakenakaEri/Are_You_Busy#5]
### 実装予定の機能
MVPまでに実装する機能を以下に記載します。

- [ ] Twitter IDでのOAuth認証機能
- [ ] TwitterIDを使用したいいね機能
- [ ] 画像のアップロード機能
- [ ] 画像の更新・削除機能
- [ ] ログイン機能
- [ ] ログアウト機能

### 必要なページ

- [ ] ヘッダー
- [ ] フッター
- [ ] メニューバー
- [ ] TOPページ
- [ ] いいねページ
- [ ] マイページ
- [ ] ログインページ
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] 利用規約

READMEに記載しているその他の機能に関しては、MVP後に実装を予定しております。

**Comment by Tsuchiya2** [comment]
LGTMです

**Comment by TakenakaEri** [comment]
ありがとうございます！
