### ISSUE TITLE
MVPリリース依頼

### ISSUE THREAD

**Issue by TakenakaEri** [TakenakaEri/Are_You_Busy#62]
## 各種情報
サービス名：Are aYou Busy?

サービスURL
https://are-you-busy.onrender.com/

GitHub URL
https://github.com/TakenakaEri/Are_You_Busy

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 自動でいいねを押す機能

- [ ] 登録したアカウントに紐づいたブックマークの表示

- [ ] 夜中の12時〜朝の5時まではサービスを停止（強制）

- [ ] ユーザー登録機能・ログイン機能

- [ ] ブックマーク機能

## READMEレビュー時から変更した機能
基本的な機能としては変更をしていないのですが、まだ実装できていない機能が沢山あります。メインのいいねを押すという機能のみ実装しました。

また、APIの仕様上、沢山の投稿にいいねすることができないので、最新のツイートを5件取得していいねを押すという内容に変更しました。なお、一度いいねを押すと、15分間はサービスが使用できないので、今後本リリースに向けては、いいねを押したいリストを作成して時間に合わせて順番に動作するようにしたり等、APIのデメリットを解消できる方法を考えて実装したいです。

## サービスイメージがわかるようなスクリーンショット等
TOP画面のサービス以外は実装できていません。
また、最大の注意点としては、一度”まとめていいね”を押すと15分間待たないと次のいいねを押せないことです...。（15分間で最大５リクエスト）

ログインボタンを押してTwitter認証でログインしてください。
その後、Twitterのユーザーネームを入力して、ツイートの取得ボタンを押してください。（ツイートの取得だけならログインしなくても取得可能です）

<img width="1439" alt="スクリーンショット 2024-06-18 20 35 43" src="https://github.com/TakenakaEri/Are_You_Busy/assets/139441655/4bd4676d-7a72-4662-a9de-c041c43f2b26">

”まとめていいね”ボタンを押すと表示されている5件のツイートにいいねが押せます

<img width="1435" alt="スクリーンショット 2024-06-18 20 36 15" src="https://github.com/TakenakaEri/Are_You_Busy/assets/139441655/a4b1a47f-a091-4f5a-957a-e91c5175fdc3">

”いいね”を押した後は”いいね済み”に変更になります

<img width="1424" alt="スクリーンショット 2024-06-18 20 36 29" src="https://github.com/TakenakaEri/Are_You_Busy/assets/139441655/3eb1fa75-b3f3-4df1-b85d-e7bda38d98e1">

**Comment by ky0613** [comment]
提出ありがとうございます。
以下コメントになります。

----

未ログイン時に`まとめていいね`を表示させない または ログインページに遷移するようにすると良いかと思います。（現時点だとエラーになってしまうので。）

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by TakenakaEri** [comment]
ありがとうございます！ご迷惑をおかけして申し訳ありません！LGTMりがとうございます！！
